### ISSUE TITLE
Update for macOS 10.12.4 or newer

### ISSUE THREAD

**Issue by myoss** [noogel/Alfred-Workflow#2]
When installing Alfred-Workflow on macOS 10.12.4 and alfred 3.5.1, alfred complains with

```
This workflow contains a python library incompatible with macOS Sierra 10.12.4+
```

please help me, thanks.

**Comment by myoss** [comment]
@noogel help me, thanks.

**Comment by noogel** [comment]
https://www.alfredapp.com/help/troubleshooting/incompatible-python-workflow-library/
 It will fix all workflows affected by the incompatibility.
